### ISSUE TITLE
Week 2 Assignment 

### ISSUE THREAD

**Issue by m-makarious** [biof509/spring2019#2]
**Part C. Subtask 1** 
When reading in the guns dataset into a Pandas data frame, the most recent year is 2019 according to the dataset whereas the assertion says the max is 2018. Can this be fixed to accurately reflect the dataset's max?

**Comment by rewaugh** [comment]
Even though the assert max is incorrect (2018, not 2019), it didn't raise an error. I even tried checking random variations, and there was no assert error with the following: 

assert guns['state'].min(), guns['year'].max() == (1998, 2018) 

which definitely should evaluate to false (would be "Alabama, 2019")

**Comment by neksa** [comment]
You are right @rewaugh 
It should be 
```
(guns['state'].min(), guns['year'].max()) == (1998, 2018)
```

I have fixed it before but somehow we've ended up with a non-corrected revision

**Comment by yeswzc** [comment]
Hi, interesting finding. 
But why 'assert' failed to find the bug? When 
```
print (guns['year'].max())
```
it says it's 2019. But the 
```
assert (guns['state'].min(), guns['year'].max()) == (1998, 2018)
``` 
do not report an error.

**Comment by neksa** [comment]
It was an incorrect assert statement

incorrect:
```
assert guns['state'].min(), guns['year'].max() == (1998, 2018)
```

correct:
```
assert (guns['state'].min(), guns['year'].max()) == (1998, 2018)
```

**Comment by yeswzc** [comment]
Finally see it. It lost the () tuple method in the first version of assignment.
Thanks!
